# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    increment_version_code(
      gradle_file_path: “app/build.gradle”
    )  
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    increment_version_code(
      gradle_file_path: “app/build.gradle”
    )
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  lane :playstore do
  gradle(task: 'clean', ) # <- Fixes it
  gradle(task: "assemble", build_type: "Release",)
  supply(track: "production", apk: "/Users/recraft-3/recraft/recraft-react-native-dating-app/android/app/build/outputs/apk/release/app-release.apk")
  upload_to_play_store(
    track: 'production',
    rollout: '0.5'
  )
  end
end
